version: "3.8"

services:
    figma-mcp:
        build:
            context: ./mpcs/figma
        ports:
            - "3000:3000"
        restart: unless-stopped
        networks:
            - mcp-network
        environment:
            - NODE_ENV=production

    git-mcp:
        build:
            context: ./mpcs/git
        ports:
            - "3005:3005"
        restart: unless-stopped
        networks:
            - mcp-network
        environment:
            - NODE_ENV=production

    github-mcp:
        build:
            context: ./mpcs/github
        ports:
            - "3002:3002"
        restart: unless-stopped
        networks:
            - mcp-network
        environment:
            - NODE_ENV=production
            - GITHUB_TOKEN=${GITHUB_TOKEN}

    notion-mcp:
        build:
            context: ./mpcs/notion
        ports:
            - "3001:3001"
        restart: unless-stopped
        networks:
            - mcp-network
        environment:
            - NODE_ENV=production
            - NOTION_TOKEN=${NOTION_TOKEN}

    memory-mcp:
        build:
            context: ./mpcs/memory
        ports:
            - "3003:3003"
        restart: unless-stopped
        networks:
            - mcp-network
        environment:
            - NODE_ENV=production

networks:
    mcp-network:
        driver: bridge
