services:
    figma-mcp:
        build:
            context: ./mcps/figma
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
        env_file:
            - .env
        restart: unless-stopped
